version: '3.7'

services:
  key_station_server:
    container_name: backend-key-station
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    env_file: ".env"
    ports:
      - "9005:9001"
    networks:
      - key_station_network
        
networks:
  key_station_network:
    driver: bridge